licenses(['notice'])

cc_library(
  name = 'test_main',
  visibility = ['//visibility:public'],
  deps = [
    '//proxygen:proxygen',
    '//external:gmock',
  ],
  srcs = [
    'TestAsyncTransport.cpp',
    'TestMain.cpp',
  ]
)
