licenses(["notice"])

cc_test(
  name = 'HPACK9Tests',
  deps = [
    '//proxygen/proxygen/lib/http/codec/compress/test:compress_test_utils',
  ],
  srcs = [
    'HPACKBufferTests.cpp',
    'HPACKCodecTests.cpp',
    'HPACKContextTests.cpp',
    'HuffmanTests.cpp',
    'RFCExamplesTests.cpp',
  ]
)
