licenses(["notice"])

cc_test(
  name = 'HTTPMessageTest',
  srcs = ['HTTPMessageTest.cpp'],
  deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
  name = 'RFC2616Test',
  srcs = ['RFC2616Test.cpp'],
  deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
  name = 'WindowTest',
  srcs = ['WindowTest.cpp'],
  deps = ['//proxygen/proxygen/lib/test:test_main']
)
