licenses(["notice"])

cc_test(
    name = 'AsyncTimeoutSetTest',
    srcs = ['AsyncTimeoutSetTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
    name = 'GenericFilterTest',
    srcs = ['GenericFilterTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
    name = 'HTTPTimeTest',
    srcs = ['HTTPTimeTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
    name = 'ParseURLTest',
    srcs = ['ParseURLTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
    name = 'ResultTest',
    srcs = ['ResultTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)

cc_test(
    name = 'UtilTest',
    srcs = ['UtilTest.cpp'],
    deps = ['//proxygen/proxygen/lib/test:test_main']
)
