cc_library(
  name = 'httpserver',
  srcs = [
    'HTTPServerAcceptor.cpp',
    'HTTPServer.cpp',
    'RequestHandlerAdaptor.cpp',
    'SignalHandler.cpp',
  ],
  deps = [
    '//proxygen/lib:proxygenlib'
  ]
)
